### PR TITLE
switch to `noarch: python`

### PR DESCRIPTION
**Pull request by carlodri**

### CODE REVIEW

**Comment by carlodri** [comment]
@jakirkham any idea why here we get those "permission denied" errors...?

**Comment by jakirkham** [comment]
How do you mean?

**Comment by jakirkham** [comment]
@conda-forge-admin, please rerender.

**Comment by jakirkham** [comment]
Maybe it’s entry point related.

**Comment by jakirkham** [comment]
Turns out we can't switch to `noarch: python` after all. `memory_profiler` may or may not install a `.bat` script depending on whether the build is on Windows or not.

**Comment by carlodri** [comment]
yeah, I see now that there's some platform-specific stuff in the package's `setup.py`. What is puzzling me is _why_ the circleci tests fail with this "permission denied" error:

```bash
/feedstock_root/build_artefacts/memory_profiler_1514240068678/test_tmp/run_test.sh: line 3: /feedstock_root/build_artefacts/memory_profiler_1514240068678/_t_env/bin/mprof: Permission denied
```

**Comment by jakirkham** [comment]
Are we ok to close this, @carlodri?

**Comment by jakirkham** [comment]
Wasn't sure at the time about the permissions denied, but I think these trace back to issue ( https://github.com/conda/conda-build/issues/2627 ). Namely `conda-build` 2.1.x wasn't preserving the executable bit on scripts copied to the package. `conda-build` 3.0.4+ handles this correctly.

**Comment by carlodri** [comment]
thanks @jakirkham, so you think I can give `noarch` another try by rerendering?

**Comment by jakirkham** [comment]
Sorry if that comment was confusing. Was try to elucidate the subtle failure mode we ran into with `conda-build`.

No unfortunately I think we are stuck here. Maybe we could encourage `memory_profiler` to start using entry points though, which could improve this in the future.

**Comment by carlodri** [comment]
oh sorry, now I get it! Thanks for the feedback.

**Pull request closed without merging**
