### PR TITLE
bump to v0.50.0

### PR DESCRIPTION
**Pull request by carlodri**

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please rerender.

**Comment by jakirkham** [comment]
Thanks @carlodri.

**Comment by carlodri** [comment]
you're welcome!

**Comment by jakirkham** [comment]
Also happy holidays.

If you have any interest in helping maintain, please feel free to add yourself as a maintainer in another PR. Can skip CI in it if you like.

**Comment by carlodri** [comment]
Merry Christmas to you as well @jakirkham, thank you!

Actually, I'm still quite new to conda-forge internals, that's why I didn't add myself yet. For instance, in this context, what I don't know is:

* how did you know you had to re-render the feedstock? did you trigger the re-render by simply pinging conda-forge-admin?
* in case I add myself with another PR, how can I opt to skip CI?

**Comment by carlodri** [comment]
by the way: shouldn't this package build be marked as `noarch`? It doesn't seem to have platform-specific code. Or does it?

**Comment by jakirkham** [comment]
Thank you.

Yeah have noticed you getting more involved here.

Pretty much we always try to re-render. It’s a safe bet it will fix CI issues. Also it’s so easy to do manually or with the bot.

I happened to know the AppVeyor issue would be fixed by re-rendering as I’m a bit more plugged into things. That said, it wouldn’t be expected that an average maintainer would know what is going on. Only that they raise the issue (probably over at `conda-smithy`).

Can just add `[ci skip]` to the commit message. Most CIs respect that. Though CircleCI has some bugs to sort out with this.

Was thinking this had C code, but I guess it doesn’t thanks to using `psutil`. Switching to `noarch: python` is a good plan. Would you like to give that a go?

**Comment by carlodri** [comment]
> Would you like to give that a go?

sure, I'm going to make a PR ASAP.

Thanks again for your kind help, I will probably bother you with some more questions sooner or later... 😉

**Pull request merged**
